{% set name = "ligo-followup-advocate" %}
{% set version = "1.1.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4c597181d07efffbb73c76cbff2dc726e28883c16b9ddd2420c1fafffb816e39

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=30.3.0
  run:
    - python >=3.6
    - astropy
    - humanize
    - jinja2
    - ligo-gracedb >=2.0.0
    - ligo.skymap
    - lxml
    - numpy

test:
  imports:
    - ligo.followup_advocate
  requires:
    - pytest
    - pytest-mock
    - setuptools
  commands:
    - python -m pytest --pyargs ligo.followup_advocate

about:
  home: https://git.ligo.org/emfollow/ligo-followup-advocate
  license: GPLv2+
  license_family: GPL
  license_file: COPYING.md
  summary: LIGO/Virgo Follow-up Advocate Tools
  description: |
    This package provides tools for LIGO/Virgo follow-up advocates to assist
    in tasks such as drafting astronomical bulletins for gravitational-wave
    detections.

extra:
  recipe-maintainers:
    - duncanmmacleod
