{% set name = "ligo-followup-advocate" %}
{% set version = "1.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 01965f3a2131086b123aabb818badc1a44ba1735ff66410b1ad411161ef52d20

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=30.3.0
  run:
    - python >=3.6
    - astropy
    - humanize
    - jinja2
    - ligo-gracedb >=2.0.0
    - ligo.skymap >=0.1.10
    - lxml
    - numpy

test:
  imports:
    - ligo.followup_advocate
  requires:
    - pip
    - pytest >=3.0
    - pytest-mock
    - setuptools
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python -m pytest -ra -v --pyargs ligo.followup_advocate

about:
  home: https://git.ligo.org/emfollow/ligo-followup-advocate
  dev_url: https://git.ligo.org/emfollow/ligo-followup-advocate.git
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.md
  summary: LIGO/Virgo Follow-up Advocate Tools
  description: |
    This package provides tools for LIGO/Virgo follow-up advocates to assist
    in tasks such as drafting astronomical bulletins for gravitational-wave
    detections.

extra:
  recipe-maintainers:
    - bpiotrzkowski
    - duncanmmacleod
