{% set name = "ligo-followup-advocate" %}
{% set version = "0.0.17" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c57f643c652ccd4a6337a3e075bf603f4a5321625e28313ceb99dd10681d6896

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - astropy
    - humanize
    - jinja2
    - ligo-gracedb >=2.0.0
    - ligo.skymap
    - lxml
    - numpy

test:
  imports:
    - ligo.followup_advocate
  requires:
    - pytest
    - pytest-mock
  commands:
    - python -m pytest --pyargs ligo.followup_advocate

about:
  home: https://git.ligo.org/emfollow/ligo-followup-advocate
  license: GPLv2+
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/COPYING.md'
  summary: LIGO/Virgo Follow-up Advocate Tools
  description: |
    This package provides tools for LIGO/Virgo follow-up advocates to assist
    in tasks such as drafting astronomical bulletins for gravitational-wave
    detections.

extra:
  recipe-maintainers:
    - duncanmmacleod
