{% set name = "ligo-followup-advocate" %}
{% set version = "1.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e1801cefad9f5dba3eca8552751e6f5aa04e403a39154f4e7a8111487f891bf5

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=30.3.0
  run:
    - python >={{ python_min }}
    - astropy-base
    - humanize
    - jinja2
    - ligo-gracedb >=2.0.0
    - ligo.skymap >=0.1.10
    - lxml
    - numpy

test:
  imports:
    - ligo.followup_advocate
  requires:
    - pip
    - pytest >=3.0
    - pytest-mock
    - setuptools
    - python {{ python_min }}
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python -m pytest -ra -v --pyargs ligo.followup_advocate

about:
  home: https://git.ligo.org/emfollow/ligo-followup-advocate
  dev_url: https://git.ligo.org/emfollow/ligo-followup-advocate.git
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.md
  summary: LIGO/Virgo Follow-up Advocate Tools
  description: |
    This package provides tools for LIGO/Virgo follow-up advocates to assist
    in tasks such as drafting astronomical bulletins for gravitational-wave
    detections.

extra:
  recipe-maintainers:
    - bpiotrzkowski
    - duncanmmacleod
