{% set name = "ligo-followup-advocate" %}
{% set version = "1.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f8ffb2b45a689790068cdeae10a38a76136f0d49835eab158e602694b52bde7d
  patches:
    # Backport https://git.ligo.org/emfollow/ligo-followup-advocate/-/merge_requests/235
    - 0001-Use-Path-relative-to-test-module-to-find-circular-te.patch

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=30.3.0
    - wheel
  run:
    - astropy-base
    - humanize
    - jinja2
    - ligo-gracedb >=2.0.0
    - ligo.skymap >=0.1.10
    - lxml
    - numpy
    - python >={{ python_min }}

test:
  files:
    - pytest.ini
  requires:
    - pip
    - pytest >=8.1
    - pytest-mock
    - python {{ python_min }}
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show ligo-followup-advocate
    # run test suite
    - python -m pytest -ra -v --pyargs ligo.followup_advocate
  imports:
    - ligo.followup_advocate

about:
  home: https://git.ligo.org/emfollow/ligo-followup-advocate
  dev_url: https://git.ligo.org/emfollow/ligo-followup-advocate.git
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING.md
  summary: LIGO/Virgo Follow-up Advocate Tools
  description: |
    This package provides tools for LIGO/Virgo follow-up advocates to assist
    in tasks such as drafting astronomical bulletins for gravitational-wave
    detections.

extra:
  recipe-maintainers:
    - bpiotrzkowski
    - duncanmmacleod
