travis:
  secure:
    BINSTAR_TOKEN: Y7UIcBLHYFV0AhhJYWW5iUoMhs3r1qLLKyiRANQvZ1WG1a4evtEcyceYUUBezW1jtwE3QhU3xzET4KX496b0YVfs48Rnt+HtVLpFATs5MAGClvEOwB8IoQ7tRfmJG4RXBtB8Q1G/95bunbssnxEAbTdSgxPwVyROoD1Z42e4VfclZnQRZ5xMS4N2XtUCaM3AdaMeLs8hBWvuc3gqMModZ847NcOYq936tziAJWdgpxhZ5i8uoakOajwzyaP1KpPwY5QGtBXadDjPnfUJcQLC1pMti0bVJklifOLhrDw/s6EbsFWyojNLgv+HjvFp0k2ivvAh+UpzAfneoVPylscpDiyXLlvPk0kv4dU8ltaevZv2Zr5iH3rZelBzxCYKjU5rhuXISu+IuR1LxlbzP9xbiFLLpbbFg93p2rYC81ThzcuC9KhfWBYJRFYmO/iPF91PqYKwr6s5S8N9pH/Y2d538pxRYJCc3AFHslnOU3HegibjZxnfEvpdXGdU+uT+tfN6psdoxQP6DmkIUr4/jfQIdF/EQ8r4NPjDwJT5nEvO5iioO64J5XTAQRZzBK0CCbMYH/Ej1PsGlzQI3t3/hhkrtP60ZukNHw1wIcgEBungAeVoBXtBAG0CWjJcxTlnyM+Q0MWi8xzQKy4ltovbj1WVqqhPWLZBu8ad37tWSZdOYS8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
